# Site settings
# These are used to personalize your new site.
title: Whitney Carpenter Algorithm # your name here
logo: "/images/senior-headshot.JPG?raw=true" # your photo (or logo) here
description: |
  Cybersecurity senior with hands-on experience in cybersecurity, systems, and full-stack software development.<br />
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cybersecurity (class of 2026)
  <br /><br />
  <a href="/pdf/Resume.pdf">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/whitney-carpenter-790761335/">View My LinkedIn Profile</a>
repository: "wbcarpenter.github.io"
github_username:  wbcarpenter # update with your username
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal  
  
  


